### PR TITLE
reST format corrections

### PR DESCRIPTION
**Pull request by andor-pierdelacabeza**
This is a bunch of commits fixing small errors on reST syntax breaking the docs:

- Broken tables
- Unescaped special characters
- Documents out of TOCs
- Old URLs...

Let me know if I went too far on any of them.

### CODE REVIEW

**Comment by andor-pierdelacabeza** [comment]
For your interest, those were the warnings I got when building with Python 3.7 and Sphinx 2.2.0. After the changes, all warnings and errors are gone.

```
sphinx-build -b singlehtml -d build/doctrees   docs build/singlehtml
Running Sphinx v2.2.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [singlehtml]: all documents
updating environment: 0 added, 12 changed, 0 removed
reading sources... [100%] security/audit/security-alert                                                                                                                                       
/docs/docs/networking/config/archiveDevice.rst:1: WARNING: Undefined substitution referenced: """".
/docs/docs/networking/config/archiveHL7Application.rst:1: WARNING: Undefined substitution referenced: """".
/docs/docs/networking/config/uiConfig.rst:44: WARNING: toctree contains reference to nonexisting document 'networking/config/uiTable'
/docs/docs/networking/specs/qido-rs/qido-rs.rst:104: WARNING: Bullet list ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:16: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:16: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:18: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:20: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:20: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:22: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:22: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:24: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:26: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:26: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:28: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:28: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:30: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:30: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:32: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:32: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:34: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:34: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:36: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:36: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:56: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:56: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:58: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:58: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:60: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:60: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:62: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:62: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:64: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:64: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:66: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:66: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:68: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:68: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:70: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:70: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:72: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:72: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:74: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:74: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:76: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:76: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:96: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:96: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:98: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:98: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:100: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:100: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:102: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:102: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:104: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:104: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:106: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:106: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:108: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:108: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:110: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:110: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:112: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:112: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:114: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:114: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:116: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:116: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:136: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:136: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:138: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:138: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:140: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:140: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:142: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:142: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:144: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:144: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:146: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:146: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:148: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:148: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:150: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:150: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:152: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:152: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:154: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:154: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:174: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:174: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:176: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:176: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:178: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:178: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:180: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:180: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:182: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:182: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:184: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:184: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:186: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:186: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:188: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:188: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:190: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:190: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:192: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:192: WARNING: Unexpected section title or transition.

----------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:212: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:212: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------------------------------------
/docs/docs/networking/specs/wado-rs.rst:214: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/networking/specs/wado-rs.rst:214: WARNING: Unexpected section title or transition.

---------------------------------------------------------------------------------------------------------
/docs/docs/networking/specs/workflow/workflow.rst:93: WARNING: Malformed table.

+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Presentation Context Table                                                                                                                         |
+--------------------------------------------------------------+-------------------------------------------------------+------+----------------------+
| Abstract Syntax                                              | Transfer Syntax                                       | Role | Extended Negotiation |
+------------------------------------+-------------------------+---------------------------------+---------------------+      +                      +
| Name                               | UID                     | Name                            | UID                 |      |                      |
+====================================+=========================+=================================+=====================+======+======================+
| Modality Performed Procedure Step  | 1.2.840.10008.3.1.2.3.3 | DICOM Implicit VR Little Endian | 1.2.840.10008.1.2   | SCU  | None                 |
+                                    +                         +---------------------------------+---------------------+      +                      +
|                                    |                         | DICOM Explicit VR Little Endian | 1.2.840.10008.1.2.1 | SCP  |                     +------------------------------------+-------------------------+---------------------------------+---------------------+------+----------------------+
+------------------------------------+-------------------------+---------------------------------+---------------------+------+----------------------+
/docs/docs/networking/specs/workflow/workflow.rst:91: WARNING: Error parsing content block for the "table" directive: exactly one table expected.

.. table:: Proposed Presentation Contexts for Real-World Activity Forward Modality Performed Procedure

   +----------------------------------------------------------------------------------------------------------------------------------------------------+
   | Presentation Context Table                                                                                                                         |
   +--------------------------------------------------------------+-------------------------------------------------------+------+----------------------+
   | Abstract Syntax                                              | Transfer Syntax                                       | Role | Extended Negotiation |
   +------------------------------------+-------------------------+---------------------------------+---------------------+      +                      +
   | Name                               | UID                     | Name                            | UID                 |      |                      |
   +====================================+=========================+=================================+=====================+======+======================+
   | Modality Performed Procedure Step  | 1.2.840.10008.3.1.2.3.3 | DICOM Implicit VR Little Endian | 1.2.840.10008.1.2   | SCU  | None                 |
   +                                    +                         +---------------------------------+---------------------+      +                      +
   |                                    |                         | DICOM Explicit VR Little Endian | 1.2.840.10008.1.2.1 | SCP  |                     +------------------------------------+-------------------------+---------------------------------+---------------------+------+----------------------+
   +------------------------------------+-------------------------+---------------------------------+---------------------+------+----------------------+
/docs/docs/security/audit/begin-transferring-dicom-instances.rst:11: WARNING: Unexpected indentation.
/docs/docs/security/audit/begin-transferring-dicom-instances.rst:13: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/security/audit/dicom-instances-transferred.rst:9: WARNING: Unexpected indentation.
/docs/docs/security/audit/dicom-instances-transferred.rst:11: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/security/audit/dicom-study-deleted.rst:9: WARNING: Unexpected indentation.
/docs/docs/security/audit/dicom-study-deleted.rst:11: WARNING: Block quote ends without a blank line; unexpected unindent.
/docs/docs/security/audit/general-message.rst:29: WARNING: "csv-table" widths do not match the number of columns in table (4).

.. csv-table:: Active Participant
   :name: audit-general-message-active-participant
   :widths: 30, 5, 65
   :header: Field Name, Opt, Description, "Additional Conditions on Field Format/Value"

    UserID, M, "Unique identifier for the user actively participating in the event."
   UserIDTypeCode, U, "Describes the identifier that is contained in User ID."
   UserTypeCode, U, "Code for the type of the user. This value is distinct from the user's role(s).", "'1'⇒'Person'"
   "", "", "", "'2'⇒'Application'"
   "AlternativeUserID", "U", "Alternative unique identifier for the user."
   "UserName", "U", "The human-meaningful name for the user."
   UserIsRequestor, M, "Indicator that the user is or is not the requestor, or initiator, for the event being audited."
   "RoleIDCode", "U", "Specification of the role(s) the user plays when performing the event, as assigned in role-based access control security."
   NetworkAccessPointTypeCode, U, "An identifier for the type of network access point."
   "NetworkAccessPointID", "M", "An identifier for the network access point of the user device This could be a device id, IP address, or some other identifier associated with a device."
/docs/docs/security/audit/security-alert.rst:147: WARNING: "csv-table" widths do not match the number of columns in table (4).

.. csv-table:: Participant Object Identification : Study
   :name: participant-object-study-impax-mismatch
   :widths: 30, 5, 65
   :header: Field Name, Opt, Description

   ParticipantObjectID, M, Study Instance UID
   ParticipantObjectTypeCode, M, System ⇒ '2'
   ParticipantObjectTypeCodeRole, M, Report ⇒ '3'
   ParticipantObjectIDTypeCode, M, "EV (110180, DCM, 'Study Instance UID')"
   ParticipantObjectDetail, U, Base-64 encoded study date if Study has StudyDate(0008,0020) attribute
   ParticipantObjectDataLifeCycle, U, OriginationCreation ⇒ '1'
   ParticipantObjectDescription, U
   SOPClass, MC, "Sop Class UID and Number of instances with this sop class. eg. <SOPClass UID='1.2.840.10008.5.1.4.1.1.88.22' NumberOfInstances='4'/>"
   Accession, U, Accession Number
looking for now-outdated files... 65 found
pickling environment... done
checking consistency... /docs/docs/networking/config/delayedCompressionRule.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
assembling single document... overview toc introduction networking networking/model networking/model/dataflow networking/model/fktdefs networking/model/fktdefs/storage networking/model/fktdefs/query-retrieve networking/model/fktdefs/workflow networking/model/fktdefs/stow-rs networking/model/fktdefs/qido-rs networking/model/fktdefs/wado-uri networking/model/fktdefs/wado-rs networking/model/fktdefs/wado-ws networking/model/activities networking/specs networking/specs/storage/storage networking/specs/query-retrieve/query-retrieve networking/specs/workflow/workflow networking/specs/stow-rs networking/specs/qido-rs/qido-rs networking/specs/wado-uri networking/specs/wado-rs networking/specs/wado-ws/wado-ws networking/interfaces networking/config networking/config/aets networking/config/params networking/config/device networking/config/networkConnection networking/config/dcmNetworkConnection networking/config/networkAE networking/config/transferCapability networking/config/dcmTransferCapability networking/config/dcmNetworkAE networking/config/archiveNetworkAE networking/config/dcmDevice networking/config/webApplication networking/config/keycloakClient networking/config/hl7Application networking/config/archiveHL7Application networking/config/imageWriter networking/config/imageReader networking/config/auditLogger networking/config/auditSuppressCriteria networking/config/auditRecordRepository networking/config/archiveDevice networking/config/attributeFilter networking/config/attributeSet networking/config/bulkData networking/config/storage networking/config/queryRetrieveView networking/config/queue networking/config/metrics networking/config/pdqService networking/config/exporter networking/config/exportRule networking/config/exportPriorsRule networking/config/rsForwardRule networking/config/keycloakServer networking/config/archiveCompressionRule networking/config/archiveAttributeCoercion networking/config/rejectionNote networking/config/studyRetentionPolicy networking/config/storeAccessControlIDRule networking/config/idGenerator networking/config/hl7ForwardRule networking/config/hl7ExportRule networking/config/hl7PrefetchRule networking/config/hl7StudyRetentionPolicy networking/config/hl7OrderScheduledStation networking/config/hl7OrderSPSStatus networking/config/uiConfig networking/config/uiAet networking/config/uiPermission networking/config/uiFilterTemplate networking/config/uiDiffConfig networking/config/uiDiffCriteria networking/config/uiDashboard networking/config/uiCompareSide networking/config/uiElasticsearch networking/config/uiElasticsearchURL networking/config/uiDeviceURL networking/config/uiDeviceCluster media charsets security security/profiles security/audit/general-message security/audit/application-activity security/audit/audit-log-used security/audit/begin-transferring-dicom-instances security/audit/data-export security/audit/dicom-instances-accessed security/audit/dicom-instances-transferred security/audit/dicom-study-deleted security/audit/query security/audit/security-alert security/audit/user-authentication security/audit/patient-record security/audit/procedure-record security/association security/application /docs/docs/networking/config/uiConfig.rst:10: WARNING: unknown document: uiTable
/docs/docs/security/audit/general-message.rst:8: WARNING: undefined label: audit-general-message-active-participant (if the link has no caption the label must precede a section header)
/docs/docs/security/audit/security-alert.rst:24: WARNING: undefined label: participant-object-study-impax-mismatch (if the link has no caption the label must precede a section header)
done
writing... done
writing additional files... done
copying images... [100%] networking/specs/storage/stgcmt-scp-seq-diagram.svg                                                                                                                  
copying static files... ... done
copying extra files... done
dumping object inventory... done
build succeeded, 128 warnings.

The HTML page is in build/singlehtml.

Build finished. The HTML page is in build/singlehtml.
```

**Comment by gunterze** [comment]
Thanks! .rst files under docs/networking/config/ are generated by running `json2rst` utility of dcm4che:
```console
$ json2rst dcm4chee-arc-light/dcm4chee-arc-ui2/src/assets/schema/device.schema.json dcm4chee-arc-cs/docs/networking/config/
dcm4chee-arc-light/dcm4chee-arc-ui2/src/assets/schema/device.schema.json => dcm4chee-arc-cs/docs/networking/config/device.rst
:
dcm4chee-arc-light/dcm4chee-arc-ui2/src/assets/schema/uiElasticsearchURL.schema.json => dcm4chee-arc-cs/docs/networking/config/uiElasticsearchURL.rst
```
I opened https://github.com/dcm4che/dcm4che/issues/528 to ensure proper encapsulation by that tool.

**Review by vrindanayak — COMMENTED** [review]
- The commit [Remove unexisting uiTable section](https://github.com/dcm4che/dcm4chee-arc-cs/pull/1/commits/734f5bf953bbfd45ae6ddc28ccf49355f1d2b623) has been reverted since the reference `uiTable` is needed in `uiConfig`.
See reference in [uiConfig.schema.json](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-ui2/src/assets/schema/uiConfig.schema.json#L95)

- The commit [Add delayedCompresionRule to tocs](https://github.com/dcm4che/dcm4chee-arc-cs/pull/1/commits/12034362840780b194afb67cc610d12688df235d) has been reverted and corresponding restructured text file has been removed, since it is no longer referenced in [archivedevice.schema.json](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-ui2/src/assets/schema/archiveDevice.schema.json) or [archiveNetworkAE.schema.json](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-ui2/src/assets/schema/archiveNetworkAE.schema.json) files.

- The commit [Fix lists](https://github.com/dcm4che/dcm4chee-arc-cs/pull/1/commits/c64cd3340ecb3529fdfcf667d1487ad82de087ba) has been further updated for [Begin Transferring DICOM Instances](https://github.com/dcm4che/dcm4chee-arc-cs/blob/master/docs/security/audit/begin-transferring-dicom-instances.rst) and [DICOM Instances Transferred](https://github.com/dcm4che/dcm4chee-arc-cs/blob/master/docs/security/audit/dicom-instances-transferred.rst) to indicate `C-Move` and `C-Get` as subtypes of Query/retrieve of objects using RAD-16

Thanks for all the remaining changes!

**Comment by andor-pierdelacabeza** [comment]
Great, thanks both for your review, I'll take a look to the rst generator :D

**Pull request merged**
